name: Build allin1 image

inputs:
  artifact_image:
    required: true
  image_tag:
    required: true
  branch:
    required: false
  pull_artifact:
    description: 'Whether to pull artifact image'
    required: false
    default: true
  for_dic:
    description: 'Whether the allin1 is for DIC purpose'
    required: false
    default: false
  clean_up_artifact_image:
    description: 'Whether to clean up the artifact image'
    required: false
    default: true

runs:
  using: composite
  steps:
    - name: GHCR login
      shell: bash
      run: |
        echo ${GITHUB_TOKEN} | docker login ghcr.io -u ${{ github.repository }} --password-stdin

    - name: Pull artifact image
      if: ${{inputs.pull_artifact == 'true'}}
      shell: bash
      run: |
        docker pull ${{inputs.artifact_image}}

    - name: Build allin1 image
      shell: bash
      run: |
        git branch

        # Need to set the flag to make Celostar compliance test pass.
        echo "empty_load_as_error = false" >> docker/dockerfiles/allin1/fe.conf

        if [[ "${{ inputs.for_dic }}" == "true" ]]; then
          echo "Adding more configs for DIC"
          {
            echo 'JAVA_OPTS="-Xms8g -Xmx64g"'
            echo "max_varchar_length = 50000000"
          } >> docker/dockerfiles/allin1/fe.conf
          {
            echo "olap_string_max_length = 50000000"
            echo "disable_storage_page_cache = true"
          } >> docker/dockerfiles/allin1/be.conf
        fi

        # Build image and always remove intermediate containers.
        DOCKER_BUILDKIT=1 docker buildx build -q --force-rm=true \
          --build-arg WITH_DEBUG_INFO=true \
          --build-arg ARTIFACTIMAGE=${{ inputs.artifact_image }} \
          -f docker/dockerfiles/allin1/allin1-ubuntu.Dockerfile \
          -t ghcr.io/celonis/celostar/starrocks-allin1:${{ inputs.image_tag }} \
          --push .

# Skip this step as we are using runs-on runner which is ephemeral.
#    - name: Clean up artifact image
#      if: ${{inputs.clean_up_artifact_image == 'true'}}
#      shell: bash
#      run: |
#        docker rmi -f $(docker images -q ${{inputs.artifact_image}})
#      continue-on-error: true

# Skip this step as we are using runs-on runner which is ephemeral.
#    - name: Clean up
#      if: ${{ always() }}
#      shell: bash
#      run: |
#        docker rmi -f $(docker images -q starrocks-allin1:${{inputs.image_tag}}) || true
#        docker system prune -f
#        docker volume prune -f
#        docker logout ghcr.io
#      continue-on-error: true
