#include <gtest/gtest.h>

#include <algorithm>
#include <random>

#include "column/array_column.h"
#include "column/column_builder.h"
#include "column/vectorized_fwd.h"
#include "explore_process_test_utils.h"
#include "exprs/agg/aggregate_factory.h"
#include "exprs/agg/nullable_aggregate.h"
#include "exprs/anyval_util.h"
#include "exprs/arithmetic_operation.h"
#include "exprs/celonis/agg/variant_stats.h"
#include "exprs/celonis/base64.h"
#include "exprs/function_context.h"
#include "modules/query/variantstats.pb.h"
#include "runtime/mem_pool.h"
#include "runtime/runtime_state.h"
#include "testutil/function_utils.h"
#include "util/slice.h"

namespace starrocks {

class CelonisExploreProcessTest : public testing::Test {
public:
    CelonisExploreProcessTest() = default;

    void SetUp() override {
        runtime_state = new RuntimeState();
        utils = new FunctionUtils(runtime_state);
        ctx = utils->get_fn_ctx();
    }

    void TearDown() override {
        delete utils;
        // FunctionUtils does not delete runtime_state.
        if (runtime_state != nullptr) {
            delete runtime_state;
        }
    }

private:
    FunctionUtils* utils{};
    FunctionContext* ctx{};
    RuntimeState* runtime_state{};
};

TEST_F(CelonisExploreProcessTest, test_equality) {
    std::string s = R"json(
        {
          "dict":[
            {
              "id":3,
              "name":"a4"
            },
            {
              "id":2,
              "name":"a3"
            },
            {
              "id":0,
              "name":"a1"
            },
            {
              "id":1,
              "name":"a2"
            }
          ],
          "a_stats":[
            {
              "count":3,
              "count_case":3,
              "count_start":3,
              "count_end":0,
              "id":0
            },
            {
              "count":3,
              "count_case":3,
              "count_start":0,
              "count_end":2,
              "id":1
            },
            {
              "count":2,
              "count_case":2,
              "count_start":1,
              "count_end":1,
              "id":2
            },
            {
              "count":1,
              "count_case":1,
              "count_start":0,
              "count_end":1,
              "id":3
            }
          ],
          "top":[
            {
              "id":0,
              "top":[
                {
                  "variant":[
                    0,
                    1
                  ],
                  "count":2
                },
                {
                  "variant":[
                    0,
                    1,
                    2
                  ],
                  "count":1
                }
              ]
            },
            {
              "id":1,
              "top":[
                {
                  "variant":[
                    0,
                    1
                  ],
                  "count":2
                },
                {
                  "variant":[
                    0,
                    1,
                    2
                  ],
                  "count":1
                }
              ]
            },
            {
              "id":2,
              "top":[
                {
                  "variant":[
                    0,
                    1,
                    2
                  ],
                  "count":1
                },
                {
                  "variant":[
                    2,
                    3
                  ],
                  "count":1
                }
              ]
            },
            {
              "id":3,
              "top":[
                {
                  "variant":[
                    2,
                    3
                  ],
                  "count":1
                }
              ]
            }
          ],
          "happy":{
            "variant":[
              0,
              1
            ],
            "count":2
          }
        }
    )json";
    ExploreProcessResult vs;
    ASSERT_TRUE(vs.from_json(s));

    // remap 0 to 1 and 1 to 0
    std::string s1 = R"json(
        {
          "dict":[
            {
              "id":3,
              "name":"a4"
            },
            {
              "id":2,
              "name":"a3"
            },
            {
              "id":1,
              "name":"a1"
            },
            {
              "id":0,
              "name":"a2"
            }
          ],
          "a_stats":[
            {
              "count":3,
              "count_case":3,
              "count_start":3,
              "count_end":0,
              "id":1
            },
            {
              "count":3,
              "count_case":3,
              "count_start":0,
              "count_end":2,
              "id":0
            },
            {
              "count":2,
              "count_case":2,
              "count_start":1,
              "count_end":1,
              "id":2
            },
            {
              "count":1,
              "count_case":1,
              "count_start":0,
              "count_end":1,
              "id":3
            }
          ],
          "top":[
            {
              "id":0,
              "top":[
                {
                  "variant":[
                    1,
                    0
                  ],
                  "count":2
                },
                {
                  "variant":[
                    1,
                    0,
                    2
                  ],
                  "count":1
                }
              ]
            },
            {
              "id":1,
              "top":[
                {
                  "variant":[
                    1,
                    0
                  ],
                  "count":2
                },
                {
                  "variant":[
                    1,
                    0,
                    2
                  ],
                  "count":1
                }
              ]
            },
            {
              "id":2,
              "top":[
                {
                  "variant":[
                    1,
                    0,
                    2
                  ],
                  "count":1
                },
                {
                  "variant":[
                    2,
                    3
                  ],
                  "count":1
                }
              ]
            },
            {
              "id":3,
              "top":[
                {
                  "variant":[
                    2,
                    3
                  ],
                  "count":1
                }
              ]
            }
          ],
          "happy":{
            "variant":[
              1,
              0
            ],
            "count":2
          }
        }
    )json";
    ExploreProcessResult vs1;
    ASSERT_TRUE(vs1.from_json(s1));
    std::cout << "\n==== vs1\n" << vs1.debug_string() << "\n===\n";

    EXPECT_TRUE(vs.equals(vs));
    EXPECT_TRUE(vs1.equals(vs1));
    EXPECT_TRUE(vs.equals(vs1));
    EXPECT_TRUE(vs1.equals(vs));
}

TEST_F(CelonisExploreProcessTest, test_no_merge) {
    auto data = {std::make_pair(build_variant_column({{"a1", "a2"}, {"a1", "a2"}, {"a1", "a2", "a3"}, {"a3", "a4"}}),
                                build_weight_column({1, 1, 1, 1}))};
    std::string rs = compute_result_explore_process(data, 0, false, ctx);

    std::string e_s = R"json(
        {
          "dict":[
            {
              "id":3,
              "name":"a4"
            },
            {
              "id":2,
              "name":"a3"
            },
            {
              "id":0,
              "name":"a1"
            },
            {
              "id":1,
              "name":"a2"
            }
          ],
          "a_stats":[
            {
              "count":3,
              "count_case":3,
              "count_start":3,
              "count_end":0,
              "id":0
            },
            {
              "count":3,
              "count_case":3,
              "count_start":0,
              "count_end":2,
              "id":1
            },
            {
              "count":2,
              "count_case":2,
              "count_start":1,
              "count_end":1,
              "id":2
            },
            {
              "count":1,
              "count_case":1,
              "count_start":0,
              "count_end":1,
              "id":3
            }
          ],
          "top":[
            {
              "id":0,
              "top":[
                {
                  "variant":[
                    0,
                    1
                  ],
                  "count":2
                },
                {
                  "variant":[
                    0,
                    1,
                    2
                  ],
                  "count":1
                }
              ]
            },
            {
              "id":1,
              "top":[
                {
                  "variant":[
                    0,
                    1
                  ],
                  "count":2
                },
                {
                  "variant":[
                    0,
                    1,
                    2
                  ],
                  "count":1
                }
              ]
            },
            {
              "id":2,
              "top":[
                {
                  "variant":[
                    0,
                    1,
                    2
                  ],
                  "count":1
                },
                {
                  "variant":[
                    2,
                    3
                  ],
                  "count":1
                }
              ]
            },
            {
              "id":3,
              "top":[
                {
                  "variant":[
                    2,
                    3
                  ],
                  "count":1
                }
              ]
            }
          ],
          "happy":{
            "variant":[
              0,
              1
            ],
            "count":2
          }
        }
    )json";
    match_result(e_s, rs);
}

TEST_F(CelonisExploreProcessTest, test_merge_with_itself) {
    auto data = {std::make_pair(build_variant_column({{}, {"key1", "key2"}, {"sr-1", "sr-2", "sr-2"}}),
                                build_weight_column({1, 2, 3})),
                 std::make_pair(build_variant_column({{}, {"key1", "key2"}, {"sr-1", "sr-2", "sr-2"}}),
                                build_weight_column({1, 2, 3}))};
    std::string rs = compute_result_explore_process(data, 0, false, ctx);

    std::string e_s = R"json(
        {
          "dict":[
            {
              "id":3,
              "name":"sr-2"
            },
            {
              "id":2,
              "name":"sr-1"
            },
            {
              "id":0,
              "name":"key1"
            },
            {
              "id":1,
              "name":"key2"
            }
          ],
          "a_stats":[
            {
              "count":4,
              "count_case":4,
              "count_start":4,
              "count_end":0,
              "id":0
            },
            {
              "count":4,
              "count_case":4,
              "count_start":0,
              "count_end":4,
              "id":1
            },
            {
              "count":6,
              "count_case":6,
              "count_start":6,
              "count_end":0,
              "id":2
            },
            {
              "count":12,
              "count_case":6,
              "count_start":0,
              "count_end":6,
              "self_loop_count_case":6,
              "id":3
            }
          ],
          "top":[
            {
              "id":0,
              "top":[
                {
                  "variant":[
                    0,
                    1
                  ],
                  "count":4
                }
              ]
            },
            {
              "id":1,
              "top":[
                {
                  "variant":[
                    0,
                    1
                  ],
                  "count":4
                }
              ]
            },
            {
              "id":2,
              "top":[
                {
                  "variant":[
                    2,
                    3,
                    3
                  ],
                  "count":6
                }
              ]
            },
            {
              "id":3,
              "top":[
                {
                  "variant":[
                    2,
                    3,
                    3
                  ],
                  "count":6
                }
              ]
            }
          ],
          "happy":{
            "variant":[
              2,
              3,
              3
            ],
            "count":6
          }
        }
    )json";
    match_result(e_s, rs);
}

TEST_F(CelonisExploreProcessTest, test_merge_distinct_dict) {
    auto data = {std::make_pair(build_variant_column({{"a1", "a2"}, {"a1", "a2", "a3"}, {"a3", "a4"}}),
                                build_weight_column({1, 2, 3})),
                 std::make_pair(build_variant_column({{"a1", "a4", "a0"}, {"a1", "a2", "a2", "a2", "a5"}}),
                                build_weight_column({4, 5}))};
    std::string rs = compute_result_explore_process(data, 0, false, ctx);

    std::string e_s = R"json(
        {
          "dict":[
            {
              "id":0,
              "name":"a0"
            },
            {
              "id":1,
              "name":"a1"
            },
            {
              "id":2,
              "name":"a2"
            },
            {
              "id":3,
              "name":"a3"
            },
            {
              "id":4,
              "name":"a4"
            },
            {
              "id":5,
              "name":"a5"
            }
          ],
          "a_stats":[
            {
              "count":4,
              "count_case":4,
              "count_start":0,
              "count_end":4,
              "id":0
            },
            {
              "count":12,
              "count_case":12,
              "count_start":12,
              "count_end":0,
              "id":1
            },
            {
              "count":18,
              "count_case":8,
              "count_start":0,
              "count_end":1,
              "self_loop_count_case":5,
              "id":2
            },
            {
              "count":5,
              "count_case":5,
              "count_start":3,
              "count_end":2,
              "id":3
            },
            {
              "count":7,
              "count_case":7,
              "count_start":0,
              "count_end":3,
              "id":4
            },
            {
              "count":5,
              "count_case":5,
              "count_start":0,
              "count_end":5,
              "id":5
            }
          ],
          "top":[
            {
              "id":0,
              "top":[
                {
                  "variant":[
                    1,
                    4,
                    0
                  ],
                  "count":4
                }
              ]
            },
            {
              "id":1,
              "top":[
                {
                  "variant":[
                    1,
                    2,
                    2,
                    2,
                    5
                  ],
                  "count":5
                },
                {
                  "variant":[
                    1,
                    4,
                    0
                  ],
                  "count":4
                },
                {
                  "variant":[
                    1,
                    2,
                    3
                  ],
                  "count":2
                },
                {
                  "variant":[
                    1,
                    2
                  ],
                  "count":1
                }
              ]
            },
            {
              "id":2,
              "top":[
                {
                  "variant":[
                    1,
                    2,
                    2,
                    2,
                    5
                  ],
                  "count":5
                },
                {
                  "variant":[
                    1,
                    2,
                    3
                  ],
                  "count":2
                },
                {
                  "variant":[
                    1,
                    2
                  ],
                  "count":1
                }
              ]
            },
            {
              "id":3,
              "top":[
                {
                  "variant":[
                    3,
                    4
                  ],
                  "count":3
                },
                {
                  "variant":[
                    1,
                    2,
                    3
                  ],
                  "count":2
                }
              ]
            },
            {
              "id":4,
              "top":[
                {
                  "variant":[
                    1,
                    4,
                    0
                  ],
                  "count":4
                },
                {
                  "variant":[
                    3,
                    4
                  ],
                  "count":3
                }
              ]
            },
            {
              "id":5,
              "top":[
                {
                  "variant":[
                    1,
                    2,
                    2,
                    2,
                    5
                  ],
                  "count":5
                }
              ]
            }
          ],
          "happy":{
            "variant":[
              1,
              2,
              2,
              2,
              5
            ],
            "count":5
          }
        }
    )json";
    match_result(e_s, rs);
}

TEST_F(CelonisExploreProcessTest, test_weights) {
    auto data = {std::make_pair(build_variant_column({{"a1", "a2"}, {"a1", "a2"}, {"a1", "a2", "a2"}, {"a3", "a4"}}),
                                build_weight_column({1, 1, 3, 2}))};
    std::string rs = compute_result_explore_process(data, 0, false, ctx);

    std::string e_s = R"json(
        {
          "dict":[
            {
              "id":3,
              "name":"a4"
            },
            {
              "id":2,
              "name":"a3"
            },
            {
              "id":0,
              "name":"a1"
            },
            {
              "id":1,
              "name":"a2"
            }
          ],
          "a_stats":[
            {
              "count":5,
              "count_case":5,
              "count_start":5,
              "count_end":0,
              "id":0
            },
            {
              "count":8,
              "count_case":5,
              "count_start":0,
              "count_end":5,
              "self_loop_count_case":3,
              "id":1
            },
            {
              "count":2,
              "count_case":2,
              "count_start":2,
              "count_end":0,
              "id":2
            },
            {
              "count":2,
              "count_case":2,
              "count_start":0,
              "count_end":2,
              "id":3
            }
          ],
          "top":[
            {
              "id":0,
              "top":[
                {
                  "variant":[
                    0,
                    1,
                    1
                  ],
                  "count":3
                },
                {
                  "variant":[
                    0,
                    1
                  ],
                  "count":2
                }
              ]
            },
            {
              "id":1,
              "top":[
                {
                  "variant":[
                    0,
                    1,
                    1
                  ],
                  "count":3
                },
                {
                  "variant":[
                    0,
                    1
                  ],
                  "count":2
                }
              ]
            },
            {
              "id":2,
              "top":[
                {
                  "variant":[
                    2,
                    3
                  ],
                  "count":2
                }
              ]
            },
            {
              "id":3,
              "top":[
                {
                  "variant":[
                    2,
                    3
                  ],
                  "count":2
                }
              ]
            }
          ],
          "happy":{
            "variant":[
              0,
              1,
              1
            ],
            "count":3
          }
        }
    )json";
    match_result(e_s, rs);
}

TEST_F(CelonisExploreProcessTest, test_empty) {
    {
        // No data.
        const AggregateFunction* func =
                get_aggregate_function("celonis_explore_process", TYPE_ARRAY, TYPE_VARCHAR, false);
        auto col1 = build_variant_column({});
        auto weights = build_weight_column({});
        auto min_variant_count_threshold_on_leaf = ColumnHelper::create_const_column<TYPE_BIGINT>(0, col1->size());
        auto enable_proto_encoding = ColumnHelper::create_const_column<TYPE_BOOLEAN>(false, col1->size());
        std::vector<const Column*> raw_columns;
        raw_columns.resize(4);
        raw_columns[0] = col1.get();
        raw_columns[1] = weights.get();
        raw_columns[2] = min_variant_count_threshold_on_leaf.get();
        raw_columns[3] = enable_proto_encoding.get();
        ctx->set_constant_columns({nullptr, nullptr, min_variant_count_threshold_on_leaf, enable_proto_encoding});
        auto state1 = ManagedAggrState::create(ctx, func);
        // Don't call update when there is no data.
        // func->update_batch_single_state(ctx, col1->size(), raw_columns.data(), state1->state());
        auto result = BinaryColumn::create();
        func->finalize_to_column(ctx, state1->state(), result.get());
        EXPECT_EQ(result->size(), 1);
        Slice slice = result->get_slice(0);
        std::string rs = slice.to_string();
        EXPECT_EQ(rs, "{}");
    }

    {
        // Only empty variant.
        auto data = {std::make_pair(build_variant_column({{}}), build_weight_column({1}))};
        std::string rs = compute_result_explore_process(data, 0, false, ctx);
        EXPECT_EQ(rs, "{}");
    }

    {
        // Single activity.
        auto data = {std::make_pair(build_variant_column({{"a1"}}), build_weight_column({1}))};
        std::string rs = compute_result_explore_process(data, 0, false, ctx);
        std::string e_s = R"json(
            {
              "dict":[
                {
                  "id":0,
                  "name":"a1"
                }
              ],
              "a_stats":[
                {
                  "count":1,
                  "count_case":1,
                  "count_start":1,
                  "count_end":1,
                  "id":0
                }
              ],
              "top":[
                {
                  "id":0,
                  "top":[
                    {
                      "variant":[
                        0
                      ],
                      "count":1
                    }
                  ]
                }
              ],
              "happy":{
                "variant":[
                  0
                ],
                "count":1
              }
            }
        )json";
        match_result(e_s, rs);
    }

    {
        // Single activity with self loop.
        auto data = {std::make_pair(build_variant_column({{"a1", "a1"}}), build_weight_column({1, 1}))};
        std::string rs = compute_result_explore_process(data, 0, false, ctx);
        std::string e_s = R"json(
            {
              "dict":[
                {
                  "id":0,
                  "name":"a1"
                }
              ],
              "a_stats":[
                {
                  "count":2,
                  "count_case":1,
                  "count_start":1,
                  "count_end":1,
                  "self_loop_count_case":1,
                  "id":0
                }
              ],
              "top":[
                {
                  "id":0,
                  "top":[
                    {
                      "variant":[
                        0,
                        0
                      ],
                      "count":1
                    }
                  ]
                }
              ],
              "happy":{
                "variant":[
                  0,
                  0
                ],
                "count":1
              }
            }
        )json";
        match_result(e_s, rs);
    }
}

TEST_F(CelonisExploreProcessTest, test_null_activity) {
    // null activity.
    auto data = {std::make_pair(build_variant_column({{"a", "null", "b"}}), build_weight_column({1}))};
    std::string rs = compute_result_explore_process(data, 0, false, ctx);
    std::string e_s = R"json(
        {
          "dict":[
            {
              "id":1,
              "name":"b"
            },
            {
              "id":0,
              "name":"a"
            }
          ],
          "a_stats":[
            {
              "count":1,
              "count_case":1,
              "count_start":1,
              "count_end":0,
              "id":0
            },
            {
              "count":1,
              "count_case":1,
              "count_start":0,
              "count_end":1,
              "id":1
            }
          ],
          "top":[
            {
              "id":0,
              "top":[
                {
                  "variant":[
                    0,
                    1
                  ],
                  "count":1
                }
              ]
            },
            {
              "id":1,
              "top":[
                {
                  "variant":[
                    0,
                    1
                  ],
                  "count":1
                }
              ]
            }
          ],
          "happy":{
            "variant":[
              0,
              1
            ],
            "count":1
          }
        }
    )json";
    match_result(e_s, rs);
}

TEST_F(CelonisExploreProcessTest, test_top_with_repeated_activities) {
    auto data = {std::make_pair(build_variant_column({{"a1", "a2"}, {"a1", "a2", "a1", "a2"}}),
                                build_weight_column({1, 10}))};
    std::string rs = compute_result_explore_process(data, 0, false, ctx);

    std::string e_s = R"json(
        {
          "dict":[
            {
              "id":0,
              "name":"a1"
            },
            {
              "id":1,
              "name":"a2"
            }
          ],
          "a_stats":[
            {
              "count":21,
              "count_case":11,
              "count_start":11,
              "count_end":0,
              "id":0
            },
            {
              "count":21,
              "count_case":11,
              "count_start":0,
              "count_end":11,
              "id":1
            }
          ],
          "top":[
            {
              "id":0,
              "top":[
                {
                  "variant":[
                    0,
                    1,
                    0,
                    1
                  ],
                  "count":10
                },
                {
                  "variant":[
                    0,
                    1
                  ],
                  "count":1
                }
              ]
            },
            {
              "id":1,
              "top":[
                {
                  "variant":[
                    0,
                    1,
                    0,
                    1
                  ],
                  "count":10
                },
                {
                  "variant":[
                    0,
                    1
                  ],
                  "count":1
                }
              ]
            }
          ],
          "happy":{
            "variant":[
              0,
              1,
              0,
              1
            ],
            "count":10
          }
        }
    )json";
    match_result(e_s, rs);
}

TEST_F(CelonisExploreProcessTest, test_self_loop) {
    auto data = {std::make_pair(build_variant_column({{"a1", "a2"}, {"a1", "a2", "a2", "a1"}}),
                                build_weight_column({1, 10}))};
    std::string rs = compute_result_explore_process(data, 0, false, ctx);

    std::string e_s = R"json(
        {
          "dict":[
            {
              "id":0,
              "name":"a1"
            },
            {
              "id":1,
              "name":"a2"
            }
          ],
          "a_stats":[
            {
              "count":21,
              "count_case":11,
              "count_start":11,
              "count_end":10,
              "id":0
            },
            {
              "count":21,
              "count_case":11,
              "count_start":0,
              "count_end":1,
              "self_loop_count_case":10,
              "id":1
            }
          ],
          "top":[
            {
              "id":0,
              "top":[
                {
                  "variant":[
                    0,
                    1,
                    1,
                    0
                  ],
                  "count":10
                },
                {
                  "variant":[
                    0,
                    1
                  ],
                  "count":1
                }
              ]
            },
            {
              "id":1,
              "top":[
                {
                  "variant":[
                    0,
                    1,
                    1,
                    0
                  ],
                  "count":10
                },
                {
                  "variant":[
                    0,
                    1
                  ],
                  "count":1
                }
              ]
            }
          ],
          "happy":{
            "variant":[
              0,
              1
            ],
            "count":1
          }
        }
    )json";
    match_result(e_s, rs);
}

TEST_F(CelonisExploreProcessTest, test_enable_proto_encoding) {
    auto data = {std::make_pair(build_variant_column({{"a1", "a2", "a3", "a4", "a5", "a6", "a7", "a00", "a01", "a02"},
                                                      {"a1", "a2", "a1", "a2"}}),
                                build_weight_column({1, 10}))};
    std::string encoded_string = compute_result_explore_process(data, 0, true, ctx);
    auto json_string = proto_to_statistics_json_string(encoded_string);
    ASSERT_TRUE(json_string.has_value());

    std::string e_s = R"json(
        {
          "dict":[
            {
              "id":3,
              "name":"a4"
            },
            {
              "id":5,
              "name":"a6"
            },
            {
              "id":4,
              "name":"a5"
            },
            {
              "id":6,
              "name":"a7"
            },
            {
              "id":9,
              "name":"a02"
            },
            {
              "id":2,
              "name":"a3"
            },
            {
              "id":7,
              "name":"a00"
            },
            {
              "id":0,
              "name":"a1"
            },
            {
              "id":1,
              "name":"a2"
            },
            {
              "id":8,
              "name":"a01"
            }
          ],
          "a_stats":[
            {
              "count":"21",
              "count_case":"11",
              "count_start":"11",
              "count_end":"0",
              "self_loop_count_case":"0",
              "id":0
            },
            {
              "count":"21",
              "count_case":"11",
              "count_start":"0",
              "count_end":"10",
              "self_loop_count_case":"0",
              "id":1
            },
            {
              "count":"1",
              "count_case":"1",
              "count_start":"0",
              "count_end":"0",
              "self_loop_count_case":"0",
              "id":2
            },
            {
              "count":"1",
              "count_case":"1",
              "count_start":"0",
              "count_end":"0",
              "self_loop_count_case":"0",
              "id":3
            },
            {
              "count":"1",
              "count_case":"1",
              "count_start":"0",
              "count_end":"0",
              "self_loop_count_case":"0",
              "id":4
            },
            {
              "count":"1",
              "count_case":"1",
              "count_start":"0",
              "count_end":"0",
              "self_loop_count_case":"0",
              "id":5
            },
            {
              "count":"1",
              "count_case":"1",
              "count_start":"0",
              "count_end":"0",
              "self_loop_count_case":"0",
              "id":6
            },
            {
              "count":"1",
              "count_case":"1",
              "count_start":"0",
              "count_end":"0",
              "self_loop_count_case":"0",
              "id":7
            },
            {
              "count":"1",
              "count_case":"1",
              "count_start":"0",
              "count_end":"0",
              "self_loop_count_case":"0",
              "id":8
            },
            {
              "count":"1",
              "count_case":"1",
              "count_start":"0",
              "count_end":"1",
              "self_loop_count_case":"0",
              "id":9
            }
          ],
          "top":[
            {
              "id":0,
              "top":[
                {
                  "variant":[
                    0,
                    1,
                    0,
                    1
                  ],
                  "count":"10"
                },
                {
                  "variant":[
                    0,
                    1,
                    2,
                    3,
                    4,
                    5,
                    6,
                    7,
                    8,
                    9
                  ],
                  "count":"1"
                }
              ]
            },
            {
              "id":1,
              "top":[
                {
                  "variant":[
                    0,
                    1,
                    0,
                    1
                  ],
                  "count":"10"
                },
                {
                  "variant":[
                    0,
                    1,
                    2,
                    3,
                    4,
                    5,
                    6,
                    7,
                    8,
                    9
                  ],
                  "count":"1"
                }
              ]
            },
            {
              "id":2,
              "top":[
                {
                  "variant":[
                    0,
                    1,
                    2,
                    3,
                    4,
                    5,
                    6,
                    7,
                    8,
                    9
                  ],
                  "count":"1"
                }
              ]
            },
            {
              "id":3,
              "top":[
                {
                  "variant":[
                    0,
                    1,
                    2,
                    3,
                    4,
                    5,
                    6,
                    7,
                    8,
                    9
                  ],
                  "count":"1"
                }
              ]
            },
            {
              "id":4,
              "top":[
                {
                  "variant":[
                    0,
                    1,
                    2,
                    3,
                    4,
                    5,
                    6,
                    7,
                    8,
                    9
                  ],
                  "count":"1"
                }
              ]
            },
            {
              "id":5,
              "top":[
                {
                  "variant":[
                    0,
                    1,
                    2,
                    3,
                    4,
                    5,
                    6,
                    7,
                    8,
                    9
                  ],
                  "count":"1"
                }
              ]
            },
            {
              "id":6,
              "top":[
                {
                  "variant":[
                    0,
                    1,
                    2,
                    3,
                    4,
                    5,
                    6,
                    7,
                    8,
                    9
                  ],
                  "count":"1"
                }
              ]
            },
            {
              "id":7,
              "top":[
                {
                  "variant":[
                    0,
                    1,
                    2,
                    3,
                    4,
                    5,
                    6,
                    7,
                    8,
                    9
                  ],
                  "count":"1"
                }
              ]
            },
            {
              "id":8,
              "top":[
                {
                  "variant":[
                    0,
                    1,
                    2,
                    3,
                    4,
                    5,
                    6,
                    7,
                    8,
                    9
                  ],
                  "count":"1"
                }
              ]
            },
            {
              "id":9,
              "top":[
                {
                  "variant":[
                    0,
                    1,
                    2,
                    3,
                    4,
                    5,
                    6,
                    7,
                    8,
                    9
                  ],
                  "count":"1"
                }
              ]
            }
          ],
          "happy":{
            "variant":[
              0,
              1,
              0,
              1
            ],
            "count":"10"
          }
        }
    )json";
    match_result(e_s, json_string.value());
}

TEST_F(CelonisExploreProcessTest, test_enable_proto_encoding_empty) {
    auto data = {std::make_pair(build_variant_column({{}}), build_weight_column({1}))};
    std::string encoded_string = compute_result_explore_process(data, 0, true, ctx);
    EXPECT_EQ("", encoded_string);
}

TEST_F(CelonisExploreProcessTest, test_drop_low_freq_variant) {
    auto data_at_leaves = {
            std::make_pair(build_variant_column({{"a1", "a2", "a2", "a3", "a4"}, // 10
                                                 {"a2", "a3"},                   // 1 (drop)
                                                 {"a3", "a4"},                   // 1 (drop)
                                                 {"a2", "a3", "a4"}}),           // 15
                           build_weight_column({10, 1, 1, 15})),
            std::make_pair(build_variant_column({{"a3", "a4"},               // 1 (drop)
                                                 {"a1", "a2", "a3", "a4"}}), // 20
                           build_weight_column({1, 20})),
    };
    std::string rs = compute_result_explore_process(data_at_leaves, 10, false, ctx);
    std::cout << rs << std::endl;
    std::string e_s = R"json(
        {
          "dict":[
            {
              "id":0,
              "name":"a1"
            },
            {
              "id":1,
              "name":"a2"
            },
            {
              "id":2,
              "name":"a3"
            },
            {
              "id":3,
              "name":"a4"
            }
          ],
          "a_stats":[
            {
              "count":30,
              "count_case":30,
              "count_start":30,
              "count_end":0,
              "id":0
            },
            {
              "count":56,
              "count_case":46,
              "count_start":16,
              "count_end":0,
              "self_loop_count_case":10,
              "id":1
            },
            {
              "count":48,
              "count_case":48,
              "count_start":2,
              "count_end":1,
              "id":2
            },
            {
              "count":47,
              "count_case":47,
              "count_start":0,
              "count_end":47,
              "id":3
            }
          ],
          "top":[
            {
              "id":0,
              "top":[
                {
                  "variant":[
                    0,
                    1,
                    2,
                    3
                  ],
                  "count":20
                },
                {
                  "variant":[
                    0,
                    1,
                    1,
                    2,
                    3
                  ],
                  "count":10
                }
              ]
            },
            {
              "id":1,
              "top":[
                {
                  "variant":[
                    0,
                    1,
                    2,
                    3
                  ],
                  "count":20
                },
                {
                  "variant":[
                    1,
                    2,
                    3
                  ],
                  "count":15
                },
                {
                  "variant":[
                    0,
                    1,
                    1,
                    2,
                    3
                  ],
                  "count":10
                }
              ]
            },
            {
              "id":2,
              "top":[
                {
                  "variant":[
                    0,
                    1,
                    2,
                    3
                  ],
                  "count":20
                },
                {
                  "variant":[
                    1,
                    2,
                    3
                  ],
                  "count":15
                },
                {
                  "variant":[
                    0,
                    1,
                    1,
                    2,
                    3
                  ],
                  "count":10
                }
              ]
            },
            {
              "id":3,
              "top":[
                {
                  "variant":[
                    0,
                    1,
                    2,
                    3
                  ],
                  "count":20
                },
                {
                  "variant":[
                    1,
                    2,
                    3
                  ],
                  "count":15
                },
                {
                  "variant":[
                    0,
                    1,
                    1,
                    2,
                    3
                  ],
                  "count":10
                }
              ]
            }
          ],
          "happy":{
            "variant":[
              0,
              1,
              2,
              3
            ],
            "count":20
          }
        }
    )json";
    match_result(e_s, rs);
}

TEST_F(CelonisExploreProcessTest, test_drop_low_freq_variant_avoid_empty_top_variants_list) {
    auto data_at_leaves = {
            std::make_pair(build_variant_column({{"a1", "a2", "a2", "a3", "a4"}, // 10
                                                 {"a2", "a3", "a5"},             // 1 (can't drop)
                                                 {"a3", "a4"},                   // 1 (drop)
                                                 {"a2", "a3", "a4"}}),           // 15
                           build_weight_column({10, 1, 1, 15})),
            std::make_pair(build_variant_column({{"a3", "a4"},   // 2 (can't drop)
                                                 {"a1", "a3"}}), // 20
                           build_weight_column({2, 20})),
    };
    std::string rs = compute_result_explore_process(data_at_leaves, 10, false, ctx);
    std::cout << rs << std::endl;
    std::string e_s = R"json(
        {
          "dict":[
            {
              "id":0,
              "name":"a1"
            },
            {
              "id":1,
              "name":"a2"
            },
            {
              "id":2,
              "name":"a3"
            },
            {
              "id":3,
              "name":"a4"
            },
            {
              "id":4,
              "name":"a5"
            }
          ],
          "a_stats":[
            {
              "count":30,
              "count_case":30,
              "count_start":30,
              "count_end":0,
              "id":0
            },
            {
              "count":36,
              "count_case":26,
              "count_start":16,
              "count_end":0,
              "self_loop_count_case":10,
              "id":1
            },
            {
              "count":49,
              "count_case":49,
              "count_start":3,
              "count_end":20,
              "id":2
            },
            {
              "count":28,
              "count_case":28,
              "count_start":0,
              "count_end":28,
              "id":3
            },
            {
              "count":1,
              "count_case":1,
              "count_start":0,
              "count_end":1,
              "id":4
            }
          ],
          "top":[
            {
              "id":0,
              "top":[
                {
                  "variant":[
                    0,
                    2
                  ],
                  "count":20
                },
                {
                  "variant":[
                    0,
                    1,
                    1,
                    2,
                    3
                  ],
                  "count":10
                }
              ]
            },
            {
              "id":1,
              "top":[
                {
                  "variant":[
                    1,
                    2,
                    3
                  ],
                  "count":15
                },
                {
                  "variant":[
                    0,
                    1,
                    1,
                    2,
                    3
                  ],
                  "count":10
                },
                {
                  "variant":[
                    1,
                    2,
                    4
                  ],
                  "count":1
                }
              ]
            },
            {
              "id":2,
              "top":[
                {
                  "variant":[
                    0,
                    2
                  ],
                  "count":20
                },
                {
                  "variant":[
                    1,
                    2,
                    3
                  ],
                  "count":15
                },
                {
                  "variant":[
                    0,
                    1,
                    1,
                    2,
                    3
                  ],
                  "count":10
                },
                {
                  "variant":[
                    2,
                    3
                  ],
                  "count":2
                },
                {
                  "variant":[
                    1,
                    2,
                    4
                  ],
                  "count":1
                }
              ]
            },
            {
              "id":3,
              "top":[
                {
                  "variant":[
                    1,
                    2,
                    3
                  ],
                  "count":15
                },
                {
                  "variant":[
                    0,
                    1,
                    1,
                    2,
                    3
                  ],
                  "count":10
                },
                {
                  "variant":[
                    2,
                    3
                  ],
                  "count":2
                }
              ]
            },
            {
              "id":4,
              "top":[
                {
                  "variant":[
                    1,
                    2,
                    4
                  ],
                  "count":1
                }
              ]
            }
          ],
          "happy":{
            "variant":[
              0,
              1,
              1,
              2,
              3
            ],
            "count":10
          }
        }
    )json";
    match_result(e_s, rs);
}

} // namespace starrocks
