apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: celostar-be
  title: celostar-be
  description: celostar-be is the backend of the query engine behind Celostar.
  tags:
    - celostar
  annotations:
    github.com/project-slug: celonis/celostar-starrocks
    argocd/app-selector: app=celostar-starrocks
    sonarqube.org/project-key: celonis_celostar-starrocks
    backstage.io/code-coverage: scm-only
    backstage.io/techdocs-entity: system:celostar
    repo-depot.celonis.dev/project-type: CUSTOM
    repo-depot.celonis.dev/image-name: celostar-starrocks/be
    repo-depot.celonis.dev/dply-release-approval-team: Celostar
    repo-depot.celonis.dev/workflow-runner-release: runner=64cpu-linux-arm64,image=ubuntu24-full-arm64,volume=150g
  links:
    - title: Celostar JIRA
      url: https://celonis.atlassian.net/jira/software/c/projects/CELOSTAR/boards/925
      icon: dashboard
      type: jira
    - title: "#celostar-support"
      url: https://grid-celonis.enterprise.slack.com/archives/C06P9DZ9FS9
      icon: group
      type: slack-channel
    - title: OpsGenie Oncall group
      url: https://celonis.app.eu.opsgenie.com/teams/dashboard/b86b4448-2e8c-4ad1-a281-9c858e4e1725/main
      icon: chat
      type: opsgenie-team
    - url: https://www.celonis.dev/docs/default/Component/celostar-wiki/runbooks/
      title: Runbook
      icon: dashboard
      type: runbook
spec:
  type: service
  lifecycle: production
  owner: group:default/celostar
  tier: "0"
  system: system:default/celostar