name: 'Build Starrocks with brpc 1.8'
run-name: Build Starrocks:${{inputs.image_tag}}-brpc1.8

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "The image tag prefix, the whole tag will have suffix of -brpc1.8"
        required: true

permissions:
  contents: read
  # Needed for the 'trilom/file-changes-action' action
  pull-requests: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

env:
  RELEASE_VERSION: "${{ inputs.image_tag }}-brpc1.8"
  IMAGE_TAG: "${{ inputs.image_tag }}-brpc1.8"
  BUILD_TYPE: Release
  GITHUB_TOKEN: ${{ secrets.CELOBOT_GITHUB_TOKEN }}
  BUILDER: ghcr.io/celonis/celostar/starrocks-dev-env:3.2-ef2f161a-locale-cpml2.177-ubuntu-brpc1.8

jobs:
  build-image:
    runs-on: [self-hosted, celostar]

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Pull dev env image
        run: |
          echo ${GITHUB_TOKEN} | docker login ghcr.io -u ${{ github.repository }} --password-stdin
          docker pull ${BUILDER}

      - name: Build artifact image
        run: |
          echo "The build type is ${BUILD_TYPE}"
          echo "The release version is ${RELEASE_VERSION}"
          echo "The artifact image tag is ${IMAGE_TAG}"
          
          # Build without starcache; otherwise it won't compile with brpc 1.8.
          sed -i 's/--enable-shared-data/--without-starcache --with-brpc-keepalive/g' docker/dockerfiles/artifacts/artifact.Dockerfile

          # Build image and always remove intermediate containers.
          DOCKER_BUILDKIT=1 docker buildx build --force-rm=true --build-arg RELEASE_VERSION=${RELEASE_VERSION} --build-arg BUILD_TYPE=${BUILD_TYPE} --build-arg builder=${BUILDER} -f docker/dockerfiles/artifacts/artifact.Dockerfile -t starrocks-artifacts:${IMAGE_TAG} .

      - name: Build allin1 image
        run: |
          # Need to set the flag to make Celostar compliance test pass.
          echo "empty_load_as_error = false" >> docker/dockerfiles/allin1/fe.conf

          # Build image and always remove intermediate containers.
          DOCKER_BUILDKIT=1 docker buildx build --force-rm=true --build-arg WITH_DEBUG_INFO=true \
            --build-arg ARTIFACTIMAGE=starrocks-artifacts:${IMAGE_TAG} \
            -f docker/dockerfiles/allin1/allin1-ubuntu.Dockerfile -t starrocks-allin1:${IMAGE_TAG} .

      - name: Push allin1 image to GHCR
        uses: ./.github/actions/push-to-registry
        with:
          local_image: starrocks-allin1:${IMAGE_TAG}
          remote_image: ghcr.io/celonis/celostar/starrocks-allin1:${IMAGE_TAG}

      - name: Build FE & BE
        uses: ./.github/actions/build-fe-be
        with:
          artifact_image: starrocks-artifacts:${IMAGE_TAG}
          image_tag: ${IMAGE_TAG}

      - name: GitHub Docker logout
        if: ${{ always() }}
        run: |
          docker logout ghcr.io

      - name: Configure prod AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: prod Amazon ECR login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push FE image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        uses: ./.github/actions/push-to-registry
        with:
          local_image: starrocks-fe:${IMAGE_TAG}
          remote_image: ${{ env.ECR_REGISTRY }}/celostar/starrocks-fe:${IMAGE_TAG}

      - name: Push BE image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        uses: ./.github/actions/push-to-registry
        with:
          local_image: starrocks-be:${IMAGE_TAG}
          remote_image: ${{ env.ECR_REGISTRY }}/celostar/starrocks-be:${IMAGE_TAG}

      - name: Clean up
        if: ${{ always() }}
        run: |
          # Delete the built docker image from the runner.
          docker rmi -f $(docker images -q starrocks-allin1:${IMAGE_TAG})
          docker rmi -f $(docker images -q starrocks-fe:${IMAGE_TAG})
          docker rmi -f $(docker images -q starrocks-be:${IMAGE_TAG})
          docker rmi -f $(docker images -q starrocks-artifacts:${IMAGE_TAG})
          
          # Delete stopped containers, dangling images, dangling build cache, etc.
          docker system prune -f
          
          # We could not simply delete the repo as it will fail the "Post checkout repository" step from the checkout action
          # after this step.
          rm -rf /runner/_work/celostar-starrocks/celostar-starrocks/*

          # Remove temporary files.
          rm -rf /tmp/*
        continue-on-error: true
