name: 'Presubmit Test'

on:
  pull_request:
    # If you update paths-ignore, please update celonis_presubmit_test_ignore.yml accordingly.
    paths-ignore:
      - '**.md'
      - '**.png'
      - 'celonis/assets/**'
      - '.github/**'
      - '!.github/workflows/celonis_presubmit_test.yml'
      - 'celonis/tools/**'
      - '!celonis/tools/presubmit/**'
      - '!celonis/tools/gtest-parallel/**'
      - 'celonis/docker/**'
      - 'docker/**'
  # To manually trigger the workflow. For debugging purpose.
  workflow_dispatch:

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

env:
  RELEASE_VERSION: presubmit-test
  GITHUB_USERNAME: ${{ github.repository }}
  GITHUB_TOKEN: ${{ secrets.CELOBOT_GITHUB_TOKEN }}
  Builder: ghcr.io/celonis/celostar/starrocks-dev-env:3.5-latest

jobs:
  presubmit-test:
    runs-on: [runs-on,runner=64cpu-linux-x64,image=ubuntu22-full-x64,disk=large,"run-id=${{ github.run_id }}"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: check Celonis's first commit
        shell: bash
        run: |
          first_commit=$(git log --grep="\[Refactor\] Transplant Celonis commits from branch-2.4-ubuntu to" --format="%H")
          
          if [ -z $first_commit ]; then
          echo "First commit Not found, existing..."
          exit 1
          else
          echo "First commit found - $first_commit"
          fi
          
          celonis_first_commit_date=$(git log $first_commit --format="%at" -n 1)
          starrocks_latest_commit_date=$(git log $first_commit^ --format="%at" -n 1)
          
          # check time
          if [ "$celonis_first_commit_date" -gt "$starrocks_latest_commit_date" ]; then
          echo "Celonis's first commit should be on the top of the latest Starrocks' commit"
          exit 1
          fi
          
          echo "Time check passed" 

      - name: Pull dev env image
        run: |
          echo ${GITHUB_TOKEN} | docker login ghcr.io -u ${{ github.repository }} --password-stdin
          docker pull ${Builder}

      - name: Test
        timeout-minutes: 60
        uses: ./.github/actions/presubmit-test
        with:
          builder: ${Builder}
