name: 'Presubmit Test'

on:
  pull_request:
    # If you update paths-ignore, please update celonis_presubmit_test_ignore.yml accordingly.
    paths-ignore:
      - '**.md'
      - '**.png'
      - 'celonis/assets/**'
      - '.github/**'
      - '!.github/workflows/celonis_presubmit_test.yml'
      - 'celonis/tools/**'
      - '!celonis/tools/presubmit/**'
      - '!celonis/tools/gtest-parallel/**'
      - 'celonis/docker/**'
      - 'docker/**'
  # To manually trigger the workflow. For debugging purpose.
  workflow_dispatch:

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

env:
  RELEASE_VERSION: presubmit-test
  GITHUB_USERNAME: ${{ github.repository }}
  GITHUB_TOKEN: ${{ secrets.CELOBOT_GITHUB_TOKEN }}
  Builder: ghcr.io/celonis/celostar/starrocks-dev-env:3.2-ef2f161a-locale-cpml2.161.2-ubuntu

jobs:
  presubmit-test:
    runs-on: [self-hosted, celostar]
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Pull dev env image
        run: |
          echo ${GITHUB_TOKEN} | docker login ghcr.io -u ${{ github.repository }} --password-stdin
          docker pull ${Builder}

      - name: Test
        uses: ./.github/actions/presubmit-test
        with:
          builder: ${Builder}
