name: Sync and rebase upstream branch
on:
  # Configuring a workflow to run manually
  workflow_dispatch:

env:
  BRANCH_3_0: branch-3.0
  GITHUB_TOKEN: ${{ secrets.CELOBOT_GITHUB_TOKEN }}

permissions:
  contents: write

jobs:
  sync-and-rebase-upstream:
    runs-on: [self-hosted, celostar]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Remote add upstream
        id: remote-add
        run: |
          git remote add upstream https://github.com/StarRocks/starrocks.git
        # Skip error of remote upstream already exists
        continue-on-error: true
      - name: Fetch upstream and push
        run: |
          git fetch upstream ${BRANCH_3_0}:${BRANCH_3_0}
          git push origin ${BRANCH_3_0}
      - name: Rebase
        run: |
          echo "Start to rebase ..."
          
          # Get the latest commit
          git fetch
          git checkout ${BRANCH_3_0}
          latest_commit=$(git rev-parse --short=8 HEAD)
          echo "The latest commit is ${latest_commit}"
          
          # Create the new default branch
          newDefaultBranch=${BRANCH_3_0}-${latest_commit}-celo
          git checkout -b ${newDefaultBranch}
          git push --set-upstream origin ${newDefaultBranch}
                    
          # Get the current default branch
          default_branch=$(git remote show origin | grep 'HEAD branch' | sed 's/^[[:space:]]*HEAD branch: //')
          echo "The current default branch is ${default_branch}"
          
          # Rebase
          git checkout ${default_branch}
          timestamp=$(date +'%Y-%m-%dT%H-%M-%S')
          echo "timestamp=$timestamp" >> $GITHUB_ENV
          git checkout -b gh-rebase-${timestamp}
          git rebase ${newDefaultBranch}
          git push --set-upstream origin gh-rebase-${timestamp}
      - name: Clean up
        if: ${{ always() }}
        run: |
          git checkout ${BRANCH_3_0}
          git branch -D gh-rebase-${{ env.timestamp }}
        continue-on-error: true