name: Build dev env image
run-name: Build dev env image ${{inputs.image_tag}}

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'The dev env image tag'
        required: true

permissions:
  contents: read
  # Needed for the 'trilom/file-changes-action' action
  pull-requests: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.CELOBOT_GITHUB_TOKEN }}
  image_tag: ${{inputs.image_tag}}

jobs:
  build-dev-env-image:
    runs-on: [runs-on,runner=32cpu-linux-x64,image=ubuntu22-full-x64,hdd=100,"run-id=${{ github.run_id }}"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: GitHub Docker login
        run: |
          echo ${GITHUB_TOKEN} | docker login ghcr.io -u ${{ github.repository }} --password-stdin

      - name: Build dev env image
        run: |
          # Check the current branch.
          branch=`git branch --show-current`
          echo "The current branch is ${branch}"

          # Build image and always remove intermediate containers.
          docker buildx build --force-rm=true --build-arg prebuild_maven=true \
            -f docker/dockerfiles/dev-env/dev-env.Dockerfile \
            -t starrocks-dev-env:${image_tag} .

      - name: Push to GHCR
        uses: ./.github/actions/push-to-registry
        with:
          local_image: starrocks-dev-env:${image_tag}
          remote_image: ghcr.io/celonis/celostar/starrocks-dev-env:${image_tag}

# Skip this step as we are using runs-on runner which is ephemeral.
#      - name: Clean up
#        if: ${{ always() }}
#        run: |
#          docker logout ghcr.io
#          docker rmi -f $(docker images -q starrocks-dev-env:${image_tag})
#
#          # Delete stopped containers, dangling images, dangling build cache, etc.
#          docker system prune -f
#          docker volume prune -f
#        continue-on-error: true
