name: 'celostar-starrocks build dev env image'

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'The dev env image tag'
        required: true

permissions:
  contents: read
  # Needed for the 'trilom/file-changes-action' action
  pull-requests: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.CELOBOT_GITHUB_TOKEN }}

jobs:
  release-ubuntu-image:
    runs-on: [self-hosted, celostar]
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: GitHub Docker login
        run: |
          echo ${GITHUB_TOKEN} | docker login ghcr.io -u ${{ github.repository }} --password-stdin

      - name: build ubuntu docker image
        run: |
          # Check the current branch.
          branch=`git branch --show-current`
          echo "The current branch is ${branch}"

          # Build image and always remove intermediate containers.
          DOCKER_BUILDKIT=1 docker build --force-rm=true -f docker/dockerfiles/dev-env/dev-env.Dockerfile -t ghcr.io/celonis/celostar/starrocks-dev-env:${{ inputs.image_tag }} .

      - name: push ubuntu docker image to GHCR
        run: |
          # Pushing to the GitHub packages docker registry regularly fails with "unknown blob" errors. The "fix" suggested by GitHub is looping.
          until docker push ghcr.io/celonis/celostar/starrocks-dev-env:${{ inputs.image_tag }}
          do
            echo "Could not push ghcr.io/celonis/celostar/starrocks-dev-env:${{ inputs.image_tag }} trying again."
          done

      - name: Clean up and GitHub Docker logout
        if: ${{ always() }}
        run: |
          docker logout ghcr.io
          docker rmi -f $(docker images -q ghcr.io/celonis/celostar/starrocks-dev-env:${{ inputs.image_tag }})
          
          # Delete stopped containers, dangling images, dangling build cache, etc.
          docker system prune -f
          docker volume prune -f
        continue-on-error: true