name: 'Ignore Presubmit Test'

on:
  pull_request:
    # If you update paths, please update celonis_presubmit_test.yml accordingly.
    paths:
      - '**.md'
      - '**.png'
      - 'celonis/assets/**'
      - '.github/**'
      - 'celonis/tools/**'
      - 'celonis/docker/**'
      - 'docker/**'
  # To manually trigger the workflow. For debugging purpose.
  workflow_dispatch:

jobs:
  presubmit-test:
    runs-on: [runs-on, runner=1cpu-linux-x64, "run-id=${{ github.run_id }}"]
    steps:
      - run: echo "No test needed"
