name: Sync rebase upstream and build dev env image

on:
  # To run manually.
  workflow_dispatch:

permissions:
  contents: write

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

env:
  LATEST_UPSTREAM_BRANCH: branch-3.1
  GITHUB_TOKEN: ${{ secrets.CELOBOT_GITHUB_TOKEN }}

jobs:
  release-ubuntu-image:
    runs-on: [self-hosted, celostar]
    steps:
      - name: Start fresh
        run: |
          echo "Deleting the existing celostar-starrocks repo"
          # We need the repo directory exist to make the checkout action work.
          rm -rf /runner/_work/celostar-starrocks; mkdir -p /runner/_work/celostar-starrocks/celostar-starrocks; echo "Deletion done"
        # Ignore not existing error
        continue-on-error: true

      - name: checkout repository
        uses: actions/checkout@v3
        # We need to ref a branch which is not the default one or ${LATEST_UPSTREAM_BRANCH} to make rebase work.
        with:
          ref: branch-3.0-c0d5082c-celo

      - name: Remote add upstream
        id: remote-add
        run: |
          git remote add upstream https://github.com/StarRocks/starrocks.git
        # Skip error of remote upstream already exists
        continue-on-error: true
      - name: Fetch upstream and push
        run: |
          git fetch upstream ${LATEST_UPSTREAM_BRANCH}:${LATEST_UPSTREAM_BRANCH}
          git push origin ${LATEST_UPSTREAM_BRANCH}
      - name: Rebase
        run: |
          echo "Start to rebase ..."

          # Get the latest commit
          git fetch
          git checkout ${LATEST_UPSTREAM_BRANCH}
          latest_commit=$(git rev-parse --short=8 HEAD)
          echo "The latest commit is ${latest_commit}"

          # Create the new default branch
          newDefaultBranch=auto-${LATEST_UPSTREAM_BRANCH}-${latest_commit}
          git checkout -b ${newDefaultBranch}

          # Get the current default branch
          default_branch=$(git remote show origin | grep 'HEAD branch' | sed 's/^[[:space:]]*HEAD branch: //')
          echo "The current default branch is ${default_branch}"

          # Rebase
          git checkout ${default_branch}
          timestamp=$(date +'%Y-%m-%dT%H-%M-%S')
          dev_env_branch=dev-env-${LATEST_UPSTREAM_BRANCH}-${latest_commit}-${timestamp}
          echo "dev_env_branch=${dev_env_branch}" >> $GITHUB_ENV
          git checkout -b $dev_env_branch
          git rebase ${newDefaultBranch}

      - name: GitHub docker login
        run: |
          echo ${GITHUB_TOKEN} | docker login ghcr.io -u ${{ github.repository }} --password-stdin

      - name: build ubuntu docker image
        run: |
          git checkout ${{ env.dev_env_branch }}
          # Use the dev_env_branch as the release version.
          # Build image and always remove intermediate containers.
          DOCKER_BUILDKIT=1 docker build --force-rm=true -f docker/dockerfiles/dev-env/dev-env.Dockerfile -t ghcr.io/celonis/celostar/starrocks-dev-env:${{ env.dev_env_branch }} .

      - name: Push docker image to GHCR
        id: push-image
        run: |
          # Pushing to the GitHub packages docker registry regularly fails with "unknown blob" errors. The "fix" suggested by GitHub is looping.
          until docker push ghcr.io/celonis/celostar/starrocks-dev-env:${{ env.dev_env_branch }}
          do
            echo "Could not push ghcr.io/celonis/celostar/starrocks-dev-env:${{ env.dev_env_branch }} trying again."
          done

      # Need this step so that create-an-issue action could find the templates.
      - name: Recheckout the repo
        if: ${{ always() }}
        uses: actions/checkout@v3

      - name: Create the failure report
        if: ${{ failure() }}
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.CELOBOT_GITHUB_TOKEN }}
        with:
          filename: .github/ISSUE_TEMPLATE/celonis_sync_rebase_build_dev_env_failure_report.md

      - name: Create the success report
        if: ${{ steps.push-image.outcome }} == 'success'
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.CELOBOT_GITHUB_TOKEN }}
        with:
          filename: .github/ISSUE_TEMPLATE/celonis_sync_rebase_build_dev_env_success_report.md

      - name: Docker logout and cleanup
        if: ${{ always() }}
        run: |
          docker logout ghcr.io
          docker rmi -f $(docker images -q ghcr.io/celonis/celostar/starrocks-dev-env:${{ env.dev_env_branch }})
          # Delete stopped containers, dangling images, dangling build cache, etc.
          docker system prune -f
          docker volume prune -f
        continue-on-error: true

      - name: Cleanup repo
        if: ${{ always() }}
        run: |
          # We need the repo directory exist so that the step "Post checkout repository" from the checkout action works
          # after this step.
          rm -rf /runner/_work/celostar-starrocks ; mkdir -p /runner/_work/celostar-starrocks/celostar-starrocks
        continue-on-error: true