name: 'celostar-starrocks release'
run-name: 'Celostar-Starrocks release: ${{ github.ref_name }}'

on:
  release:
    types: [published]

permissions:
  contents: write
  # Needed for the 'trilom/file-changes-action' action
  pull-requests: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

env:
  RELEASE_VERSION: ${{ github.ref_name }}
  IMAGE_TAG: ${{ github.ref_name }}
  BUILD_TYPE: Release
  ASAN_RELEASE_VERSION: "${{ github.ref_name }}-asan"
  ASAN_IMAGE_TAG: "${{ github.ref_name }}-asan"
  ASAN_BUILD_TYPE: ASAN
  GITHUB_TOKEN: ${{ secrets.CELOBOT_GITHUB_TOKEN }}
  GITHUB_USERNAME: ${{ github.repository }}
  BUILDER: ghcr.io/celonis/celostar/starrocks-dev-env:mul-arch-dev-env

jobs:
  build-arm:
    runs-on: [ runs-on, runner=64cpu-linux-arm64, image=ubuntu24-full-arm64, disk=large, "run-id=${{ github.run_id }}" ]
    env:
      image_tag: ${{ github.ref_name }}-arm
    outputs:
      artifact_image_tag: ${{ env.image_tag }}
      allin1_image: ${{ env.image_tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull dev env image
        run: |
          echo ${{ env.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository }} --password-stdin
          docker pull ${{ env.BUILDER }}
      - name: Build artifact image
        id: build-artifact
        uses: ./.github/actions/build-artifact
        with:
          dev_env_image: ${{ env.BUILDER }}
          image_tag: ${{ env.image_tag }}
          to_push: 'false'

      - name: Build and push allin1 image
        uses: ./.github/actions/build-allin1
        with:
          artifact_image: starrocks-artifacts:${{ env.image_tag }}
          image_tag: ${image_tag}
          pull_artifact: 'false'

      - name: Build and push fe-be
        uses: ./.github/actions/build-fe-be
        with:
          artifact_image: starrocks-artifacts:${{ env.image_tag }}
          image_tag: ${{ env.image_tag }}
          to_push: 'true'
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  build-x86:
    runs-on: [ runs-on, runner=64cpu-linux-x64, image=ubuntu24-full-x64, disk=large, "run-id=${{ github.run_id }}" ]
    env:
      image_tag: ${{ github.ref_name }}-x86
    outputs:
      artifact_image_tag: ${{ env.image_tag }}
      allin1_image: ${{ env.image_tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build artifact image
        id: build-artifact
        uses: ./.github/actions/build-artifact
        with:
          dev_env_image: ${{ env.BUILDER }}
          image_tag: ${{ env.image_tag }}
          to_push: 'false'

      - name: Build and push allin1 image
        uses: ./.github/actions/build-allin1
        with:
          artifact_image: starrocks-artifacts:${{ env.image_tag }}
          image_tag: ${{ env.image_tag }}
          pull_artifact: 'false'

      - name: Build and push fe-be
        uses: ./.github/actions/build-fe-be
        with:
          artifact_image: starrocks-artifacts:${{ env.image_tag }}
          image_tag: ${{ env.image_tag }}
          to_push: 'true'
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Publish fe artifacts to GitHub Packages
        if: ${{ !github.event.release.draft && !github.event.release.prerelease }}
        continue-on-error: true
        uses: ./.github/actions/publish-fe-artifacts
        with:
          artifact_image: starrocks-artifacts:${{ env.image_tag }}
          token: ${{ secrets.CELOBOT_GITHUB_TOKEN }}

  build-and-push-manifest:
    runs-on: [runs-on, runner=1cpu-linux-arm64, "run-id=${{ github.run_id }}"]
    needs: [build-arm, build-x86]
    env:
      arm_image_tag: ${{ needs.build-arm.outputs.allin1_image }}
      x86_image_tag: ${{ needs.build-x86.outputs.allin1_image }}
      allin1_image_tag: ${{ github.ref_name }}
      fe_be_image_tag: ${{ github.ref_name }}
    outputs:
      allin1_image_tag: ${{ env.allin1_image_tag }}
      fe_be_image_tag: ${{ env.fe_be_image_tag }}
    steps:
      - name: GHCR login
        shell: bash
        run: |
          echo ${GITHUB_TOKEN} | docker login ghcr.io -u ${GITHUB_USERNAME} --password-stdin
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and push allin1 manifest
        uses: ./.github/actions/build-mul-arch-manifest
        with:
          arm_image_tag: "ghcr.io/celonis/celostar/starrocks-allin1:${arm_image_tag}"
          x86_image_tag: "ghcr.io/celonis/celostar/starrocks-allin1:${x86_image_tag}"
          mul_arch_image_tag: "ghcr.io/celonis/celostar/starrocks-allin1:${allin1_image_tag}"
      - name: Build and push fe-be manifest
        shell: bash
        run: |
          echo ${GITHUB_TOKEN} | docker login ghcr.io -u ${GITHUB_USERNAME} --password-stdin
          export DOCKER_CLI_EXPERIMENTAL=enabled

          mul_arch_tag="ghcr.io/celonis/celostar/starrocks-be:${fe_be_image_tag}"
          arm_tag="ghcr.io/celonis/celostar/starrocks-be:${arm_image_tag}"
          x86_tag="ghcr.io/celonis/celostar/starrocks-be:${x86_image_tag}"

          docker manifest create "$mul_arch_tag" --amend "$arm_tag" --amend "$x86_tag"

          docker manifest push "$mul_arch_tag"
          
          mul_arch_tag="ghcr.io/celonis/celostar/starrocks-fe:${fe_be_image_tag}"
          arm_tag="ghcr.io/celonis/celostar/starrocks-be:${arm_image_tag}"
          x86_tag="ghcr.io/celonis/celostar/starrocks-be:${x86_image_tag}"

          docker manifest create "$mul_arch_tag" --amend "$arm_tag" --amend "$x86_tag"

          docker manifest push "$mul_arch_tag"

      - name: Configure prod AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: prod Amazon ECR login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push fe-be manifest to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        uses: ./.github/actions/build-mul-arch-manifest
        with:
          arm_image_tag: "${{ env.ECR_REGISTRY }}/celostar/starrocks-be:${arm_image_tag}"
          x86_image_tag: "${{ env.ECR_REGISTRY }}/celostar/starrocks-be:${x86_image_tag}"
          mul_arch_image_tag: "${{ env.ECR_REGISTRY }}/celostar/starrocks-be:${fe_be_image_tag}"

      - name: Build and push fe manifest to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        uses: ./.github/actions/build-mul-arch-manifest
        with:
          arm_image_tag: "${{ env.ECR_REGISTRY }}/celostar/starrocks-fe:${arm_image_tag}"
          x86_image_tag: "${{ env.ECR_REGISTRY }}/celostar/starrocks-fe:${x86_image_tag}"
          mul_arch_image_tag: "${{ env.ECR_REGISTRY }}/celostar/starrocks-fe:${fe_be_image_tag}"

  build-asan-allin1-image:
    runs-on: [runs-on,runner=64cpu-linux-x64,image=ubuntu22-full-x64,disk=large,"run-id=${{ github.run_id }}"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull dev env image
        run: |
          echo ${GITHUB_TOKEN} | docker login ghcr.io -u ${{ github.repository }} --password-stdin
          docker pull ${{ env.BUILDER }}

      - name: Build ASAN artifact image
        uses: ./.github/actions/build-artifact
        with:
          dev_env_image: ${{ env.BUILDER }}
          image_tag: ${{ env.ASAN_IMAGE_TAG }}
          is_asan_mode: 'yes'
          to_push: true

      - name: Build and push ASAN allin1 image
        uses: ./.github/actions/build-allin1
        with:
          artifact_image: ghcr.io/celonis/celostar/starrocks-artifacts:${ASAN_IMAGE_TAG}
          image_tag: ${{ env.ASAN_IMAGE_TAG }}
          pull_artifact: false
