name: Sync upstream branch
on:
  schedule:
    # At 00:00.
    - cron:  '0 0 * * *'
  # Configuring a workflow to run manually
  workflow_dispatch:

env:
  LATEST_UPSTREAM_BRANCH: branch-3.1
  GITHUB_TOKEN: ${{ secrets.CELOBOT_GITHUB_TOKEN }}

permissions:
  contents: write

jobs:
  sync-branch:
    runs-on: [self-hosted, celostar]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Sync upstream commits
        run: |
          git branch
          git remote add upstream https://github.com/StarRocks/starrocks.git
          git remote -v
          git fetch upstream ${LATEST_UPSTREAM_BRANCH}:${LATEST_UPSTREAM_BRANCH}
          git push origin ${LATEST_UPSTREAM_BRANCH}
