name: Sync upstream branch
on:
  schedule:
    # At 00:00.
    - cron:  '0 0 * * *'
  # Configuring a workflow to run manually
  workflow_dispatch:

env:
  LATEST_UPSTREAM_BRANCH: branch-3.3
  BRANCH_3_3: branch-3.3
  MAIN: main
  GITHUB_TOKEN: ${{ secrets.CELOBOT_GITHUB_TOKEN }}

permissions:
  contents: write

jobs:
  sync-branch:
    runs-on: [runs-on, runner=1cpu-linux-x64, image=ubuntu22-full-x64, "run-id=${{ github.run_id }}"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Remote add upstream
        id: remote-add
        run: |
          git branch
          git remote add upstream https://github.com/StarRocks/starrocks.git

      - name: Fetch upstream ${{env.LATEST_UPSTREAM_BRANCH}}
        run: |
          git remote -v
          git fetch upstream ${LATEST_UPSTREAM_BRANCH}:${LATEST_UPSTREAM_BRANCH}
          git push origin ${LATEST_UPSTREAM_BRANCH}

      - name: Fetch upstream ${{env.MAIN}}
        run: |
          git remote -v
          git fetch upstream ${MAIN}:${MAIN}
          git push origin ${MAIN}

      - name: Fetch upstream ${{env.BRANCH_3_3}}
        run: |
          git remote -v
          git fetch upstream ${BRANCH_3_3}:${BRANCH_3_3}
          git push origin ${BRANCH_3_3}
