name: Sync upstream branch
on:
  schedule:
    # At 00:00.
    - cron:  '0 0 * * *'
  # Configuring a workflow to run manually
  workflow_dispatch:

env:
  BRANCH_2_5: branch-2.5
  BRANCH_3_0: branch-3.0

permissions:
  contents: write

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Sync upstream commits
        run: |
          git branch
          git remote add upstream https://github.com/StarRocks/starrocks.git
          git remote -v
          git fetch upstream ${BRANCH_2_5}:${BRANCH_2_5}
          git push origin ${BRANCH_2_5}
          git fetch upstream ${BRANCH_3_0}:${BRANCH_3_0}
          git push origin ${BRANCH_3_0}
