name: 'Ignore Presubmit Test'

on:
  pull_request:
    # If you update paths, please update celonis_presubmit_test.yml accordingly.
    paths:
      - '**.md'
      - '**.png'
      - 'celonis/assets/**'
  # To manually trigger the workflow. For debugging purpose.
  workflow_dispatch:

jobs:
  presubmit-test:
    runs-on: [self-hosted, celostar]
    steps:
      - run: echo "No test needed"